### ISSUE TITLE
Allow to change the commit rule

### ISSUE THREAD

**Issue by Iltotore** [Wafelack/genlog#3]
By default, genlog uses the rule `<scope>: <description>`. But we should be able to use our own rule like:

```sh
genlog.sh <tag> --rule "[{scope}]: {description}"
```

**Comment by Wafelack** [comment]
This changelog generator is initially made for the [skiftOS](https://github.com/skiftOS/skiftOS) commit rule, so changing it wouldn't be that good. Moreover, string manipulation in bash is truly awful, so parsing that and generating the code would be pretty hard.
